### ISSUE TITLE
code

### ISSUE THREAD

**Issue by xiaojiebangbang** [iSEE-Laboratory/DiffUIR#10]
![git](https://github.com/user-attachments/assets/81c21613-6cd3-4988-b649-b15b84cff9c2)
这个参数你代码里直接是0.1，但是如果按照论文的说法，这个参数应该是1，原因是什么？

**Comment by zhengdian1** [comment]
Yes, you are right, we follow RDDM to use this value, which could obtain better results. We think this is an interesting point to deep in.
