### ISSUE TITLE
Could you tell me why I can only get such results, if something wrong with the config?

### ISSUE THREAD

**Issue by MaoAYD** [iSEE-Laboratory/DiffUIR#12]
![02](https://github.com/user-attachments/assets/ebc5037e-4b45-4d60-93a4-0406bd01fba6)
![image](https://github.com/user-attachments/assets/3a6a86ad-7771-4044-a6f8-1997bfbbc8b1)

**Comment by MaoAYD** [comment]
I found the problem. The wrong path to read weights causes no weights to be loaded, but there is no error warning

**Comment by zhoushen1** [comment]
> 我找到了问题所在。读取权重的错误路径会导致无法加载权重，但没有错误警告

您好呀！我也遇到了相同的问题，请问您是如何解决的呢？

**Comment by Threegood-student** [comment]
> I found the problem. The wrong path to read weights causes no weights to be loaded, but there is no error warning

您好呀！我也遇到了相同的问题，请问您是怎么解决的呢？

**Comment by zhengdian1** [comment]
We upload the instruction of test.py and visual.py in readme, try again.
