### ISSUE TITLE
关于实验的问题

### ISSUE THREAD

**Issue by spec350** [iSEE-Laboratory/DiffUIR#13]
![image](https://github.com/user-attachments/assets/14fd4f94-27bf-44c1-b733-27c19adf31e9)
作者您好，为什么表中有些指标没有

**Comment by zhengdian1** [comment]
task-specific的方法基本都是做单任务的，我们report了他们提供的任务的结果。universal的方法我们复现了其中的几篇，剩余几篇由于不开源以及时间原因只report了他们论文中给的任务的结果。在论文中有写明这几点

**Comment by spec350** [comment]
> task-specific的方法基本都是做单任务的，我们report了他们提供的任务的结果。universal的方法我们复现了其中的几篇，剩余几篇由于不开源以及时间原因只report了他们论文中给的任务的结果。在论文中有写明这几点

task-specific的方法是指训练的时候把不同任务的数据集分开训练，训练出多个model，universal是指训练的时候把不同任务的数据集放在一起训练，训练出一个统一的model？

**Comment by zhengdian1** [comment]
建议您先去看一下图像恢复里面任务的分类，您的理解是基本正确的，但是需要注意，task-specific的方法和universal的方法一般是不互通的，不能简单理解为universal的方法可以分开来训练变成task-specific的方法，task-specific的方法一般会包含一个特定任务的先验（例如早期去雨任务会蕴含雨线detection），所以一般不能adapt到其他任务

**Comment by spec350** [comment]
> 建议您先去看一下图像恢复里面任务的分类，您的理解是基本正确的，但是需要注意，task-specific的方法和universal的方法一般是不互通的，不能简单理解为universal的方法可以分开来训练变成task-specific的方法，task-specific的方法一般会包含一个特定任务的先验（例如早期去雨任务会蕴含雨线detection），所以一般不能adapt到其他任务

好的，谢谢

**Comment by spec350** [comment]
> task-specific的方法基本都是做单任务的，我们report了他们提供的任务的结果。universal的方法我们复现了其中的几篇，剩余几篇由于不开源以及时间原因只report了他们论文中给的任务的结果。在论文中有写明这几点

作者您好，我并没有发现您的论文中写了这些，能否告知一下写在了具体哪部分
