### ISSUE TITLE
LOL dataset  results were not noticeable

### ISSUE THREAD

**Issue by lanpokn** [iSEE-Laboratory/DiffUIR#14]
I tried to test the low-light enhancement task on the LOL dataset with visualize.py, and the results were not noticeable, and the image was basically unchanged, why is that? (I have tested Gopro dataset and it is good)
 before:
![112](https://github.com/user-attachments/assets/f4d8862b-1855-49e3-a3a2-f2af512b0a6f)
after:
![temp1](https://github.com/user-attachments/assets/3a9c8e13-52cd-44cf-92d8-14915851fc5d)

**Comment by zhengdian1** [comment]
Note that if you want to test low-light image, please use the code src/visualization-Line1279-1281

**Comment by lanpokn** [comment]
lines 1279-1281:
      “self.ema.to(self.device)
        print("test start")
        if self.condition”
       
       It seems that as long as `visual.py` is called, what is actually invoked is `src/visualization` at lines 1279-1281 . Therefore, it appears that calling these lines directly may not resolve the issue.

**Comment by zhengdian1** [comment]
The code is modified one times, if you git recently, it should be lines 1286-1288
