### ISSUE TITLE
Sorry for bothering, when I tested the dataset with pretrained 300.pt, the output results were bad. Do any parameters of the test.py need to be adjusted? Thank you guys

### ISSUE THREAD

**Issue by ChiyuanLin** [iSEE-Laboratory/DiffUIR#16]
Sorry for bothering, when I tested the dataset with pretrained 300.pt, the output results were bad. Do any parameters of the test.py need to be adjusted? Thank you guys
![GOPR0384_11_00-000002 png](https://github.com/user-attachments/assets/9b57d734-4ec0-441d-b6f2-bf031167757b)
![scene002-2 png](https://github.com/user-attachments/assets/d8fb1886-8185-440a-a705-1eaf8a958fe4)

_Originally posted by @ChiyuanLin in https://github.com/iSEE-Laboratory/DiffUIR/issues/7#issuecomment-2352766327_

**Comment by zhengdian1** [comment]
In my view, you do not load the model correctly

**Comment by ChiyuanLin** [comment]
> In my view, you do not load the model correctly

Thank you for your reply. I loaded the large model 300.pt, and directly ran the test  file.  Is there something new that needs to be changed?

**Comment by zhengdian1** [comment]
You are testing dehazing task, so you should change the 'task' in https://github.com/iSEE-Laboratory/DiffUIR/blob/3d762347cae66e260fc51f8e1702fd8273113538/test.py#L43 to blur

**Comment by zhengdian1** [comment]
You are testing debluring task, so you should change the 'task' to blur https://github.com/iSEE-Laboratory/DiffUIR/blob/3d762347cae66e260fc51f8e1702fd8273113538/test.py#L43

**Comment by ChiyuanLin** [comment]
> You are testing debluring task, so you should change the 'task' to blur
> 
> https://github.com/iSEE-Laboratory/DiffUIR/blob/3d762347cae66e260fc51f8e1702fd8273113538/test.py#L43

Thank you, I have changed the task, and the results I uploaded were the output under "blur" task.
![image](https://github.com/user-attachments/assets/3b4c65cf-ce6a-4cdf-a418-5a4f08aa26ba)

**Comment by ChiyuanLin** [comment]
> > You are testing debluring task, so you should change the 'task' to blur
> > https://github.com/iSEE-Laboratory/DiffUIR/blob/3d762347cae66e260fc51f8e1702fd8273113538/test.py#L43
> 
> Thank you, I have changed the task, and the results I uploaded were the output under "blur" task. ![image](https://private-user-images.githubusercontent.com/79588748/367987934-3b4c65cf-ce6a-4cdf-a418-5a4f08aa26ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NDIwMjQsIm5iZiI6MTcyNjU0MTcyNCwicGF0aCI6Ii83OTU4ODc0OC8zNjc5ODc5MzQtM2I0YzY1Y2YtY2U2YS00Y2RmLWE0MTgtNWE0ZjA4YWEyNmJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDAyNTUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyZjllZWM0MTliODhiMmMxODUwOWJiMDZlMWNlZjg3MzA1ZWM3Nzg5ZWJiY2MxMTU3NmM0MWNjZDYwZTU0M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wj7vdd_CXpGfX0sW2MQeHdFVlj6CUSdpnKqlod1mqCs)

I found the problem, the model didn’t load the weights, thank you !

**Comment by ZhuLiangyu123** [comment]
> > > You are testing debluring task, so you should change the 'task' to blur
> > > 
> > >   
> > >     
> > >       [DiffUIR/test.py](https://github.com/iSEE-Laboratory/DiffUIR/blob/3d762347cae66e260fc51f8e1702fd8273113538/test.py#L43)
> > >     
> > >     
> > >          Line 43
> > >       in
> > >       [3d76234](/iSEE-Laboratory/DiffUIR/commit/3d762347cae66e260fc51f8e1702fd8273113538)
> > >     
> > >   
> > >   
> > >     
> > > 
> > >         
> > >           
> > >            dataset = AlignedDataset_all(opt, image_size, augment_flip=False, equalizeHist=True, crop_patch=False, generation=False, task='fog')
> > 
> > 
> > Thank you, I have changed the task, and the results I uploaded were the output under "blur" task. ![image](https://private-user-images.githubusercontent.com/79588748/367987934-3b4c65cf-ce6a-4cdf-a418-5a4f08aa26ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NDIwMjQsIm5iZiI6MTcyNjU0MTcyNCwicGF0aCI6Ii83OTU4ODc0OC8zNjc5ODc5MzQtM2I0YzY1Y2YtY2U2YS00Y2RmLWE0MTgtNWE0ZjA4YWEyNmJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDAyNTUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyZjllZWM0MTliODhiMmMxODUwOWJiMDZlMWNlZjg3MzA1ZWM3Nzg5ZWJiY2MxMTU3NmM0MWNjZDYwZTU0M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wj7vdd_CXpGfX0sW2MQeHdFVlj6CUSdpnKqlod1mqCs)
> 
> I found the problem, the model didn’t load the weights, thank you !

您好，我也出现了这个问题，想请问一下这个模型的权重该如何加载？
