### ISSUE TITLE
咨询代码问题！

### ISSUE THREAD

**Issue by jjjjjgggj** [iSEE-Laboratory/DiffUIR#17]
作者你好！我在研究这篇论文时，在看源代码时，发现这条式子始终和论文对不上
![屏幕截图 2024-09-24 193546](https://github.com/user-attachments/assets/f09711b6-ba1e-45f2-b176-0f7187f1c5ac)

![屏幕截图 2024-09-24 193546](https://github.com/user-attachments/assets/d9759af4-59e9-4171-a911-f17925d459b5)
self.delta_cumsum[-1]这个在代码中应该是1吧。

**Comment by zhengdian1** [comment]
按照公式推导这一项确实应该是1，我们follow的RDDM的源代码，发现推理的时候把噪声系数调成一个很小的值会有更好的效果

**Comment by jjjjjgggj** [comment]
如果是1的话，那整个公式最后是不是就可以写成 img = 0.1 * torch.randn

**Comment by zhengdian1** [comment]
不是，请您认真阅读我们的论文以及代码，您甚至可以断点调试一下每个参数的值，这样对您更有帮助
