### ISSUE TITLE
一些分布式训练相关问题

### ISSUE THREAD

**Issue by huaqlili** [iSEE-Laboratory/DiffUIR#21]
作者您好，了解到您的代码是在单gpu的模式上构建的，如果我想要用8卡同时训练的话，需要改动哪些地方呢？
目前，我将定义的unetres封装为model = torch.nn.parallel.DistributedDataParallel(model)，但是这样是无法运行的。
感谢您的工作，希望得到您的尽快回复

**Comment by zhengdian1** [comment]
我没有试过多卡，但就是正常的扩散模型训练，你看看报错自己debug一下就好了
