### ISSUE TITLE
关于训练集问题

### ISSUE THREAD

**Issue by xiaojiebangbang** [iSEE-Laboratory/DiffUIR#3]
你好！想问下你的训练集中是把不同任务的数据都放进去了吗，比如含雨、雾、阴影这种不同类型的数据，是否是在一次训练中全都放进去呢？

**Comment by zhengdian1** [comment]
是的，我们每个batch会同时包含所有类型的退化数据，同时会按照不同退化任务数据集的比例分配每个batch中的数量，具体代码在src/model.py Line1208

**Comment by xiaojiebangbang** [comment]
谢谢解答！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Dian Zheng ***@***.***&gt;
发送时间: 2024年4月19日 19:10
收件人: iSEE-Laboratory/DiffUIR ***@***.***&gt;
抄送: xiaojiebangbang ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [iSEE-Laboratory/DiffUIR] 关于训练集问题 (Issue #3)





 
是的，我们每个batch会同时包含所有类型的退化数据，同时会按照不同退化任务数据集的比例分配每个batch中的数量，具体代码在src/model.py Line1208

**Comment by xiaojiebangbang** [comment]
accelarate没有将数据放到Gpu上运行该怎么解决？（model脚本第1233行）
os.environ[cuda_visible_device]我设置了0，源代码是6，因为我的服务器只有0，1两块gpu

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Dian Zheng ***@***.***&gt;
发送时间: 2024年4月19日 19:11
收件人: iSEE-Laboratory/DiffUIR ***@***.***&gt;
抄送: xiaojiebangbang ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [iSEE-Laboratory/DiffUIR] 关于训练集问题 (Issue #3)





 
Closed #3 as completed.
