### ISSUE TITLE
name 'cv2equalizeHist' is not defined

### ISSUE THREAD

**Issue by 15735347877** [iSEE-Laboratory/DiffUIR#4]
"Hello, may I ask if the code src/visualization-Line1279-1281 where input_image = cv2equalizeHist(input_image) is used for testing low-light images, is the function cv2equalizeHist written by the author? If it is a custom function, it is not present in the code; if not, calling cv2.equalizeHist can only perform histogram equalization on grayscale images? This piece of code will cause an error. I look forward to the author's reply."
![bb0593c5d0bc24df70e0d02c2be4241](https://github.com/iSEE-Laboratory/DiffUIR/assets/117496923/c8986618-db3c-466d-a7a4-aa23f5889a7a)

**Comment by zhengdian1** [comment]
Thank you for pointing out. We have updated the visualization.py and added the cv2equalizeHist function

**Comment by 15735347877** [comment]
Oh,thanks for your answer.
