### ISSUE TITLE
Snow100K download link expired.

### ISSUE THREAD

**Issue by xuyimin0926** [iSEE-Laboratory/DiffUIR#6]
Hi,

Thanks for your awesome work! However, the provided link of the Snow100k dataset is no longer available, can you help figure it out? 

Thanks!

**Comment by zhengdian1** [comment]
It seems that the official source of the dataset dismissed, but I do not have enough room to upload it into google drive. Please wait for some time or search other sources.

**Comment by Ly403** [comment]
Hi @zhengdian1 and @xuyimin0926,

Thanks for your information about this issue.

I noticed that the URL provided by @sunshangquan in [Histoformer Issues#2](https://github.com/sunshangquan/Histoformer/issues/2) only contains a subset (18,068 images) of the **Snow100K training data**.

However, the DiffUIR paper mentions using the full training set, and I'm curious if there are any other sources to download the complete **Snow100K training dataset**.

Any help would be greatly appreciated! Thank you again!
