### ISSUE TITLE
关于一些代码的疑惑

### ISSUE THREAD

**Issue by xiaojiebangbang** [iSEE-Laboratory/DiffUIR#7]
你好！请问model.py中将x_input*2-1的作用是什么？以及在测试时（img = (1-self.delta_cumsum[-1]) * x_input + self.betas_cumsum[-1] * torch.randn(shape, device=device)）  ，然后将这部分和输入拼接送进网络，这部分原因不是很理解。求大佬解答！

**Comment by zhengdian1** [comment]
这是diffusion固定的输入格式，-1，1，这样才能和高斯噪声保持一致的数值变化，还是那句话，一定要先了解扩散模型的基础原理和公式再来看我们的文章，只看代码是没有用的
